#!/bin/sh

backup_file=/data/os_backup/os_backup_`date +%Y%m%d`

if [ $(id -u) -ne 0 ]
then
	echo "Please run as root."
	exit
fi

echo ""
echo "Backup OS to $backup_file (not including /home)"
sleep 3

echo "List files or directories: >1MB"
du -sh /* | egrep -v '[[:digit:]]K\s|0'
du -sh /.* | egrep -v '[[:digit:]]K\s|0|'

sleep 10

set -v on

tar -cvPzf $backup_file.tgz \
--exclude=/proc \
--exclude=/dev \
--exclude=/mnt \
--exclude=/media \
--exclude=/lost+found \
--exclude=/cdrom \
--exclude=/tmp \
--exclude=/sys \
--exclude=/run \
--exclude=/data \
--exclude=/home \
/ \
> $backup_file.log \
2> $backup_file.error
