#!/bin/sh
alias vncserver='vncserver -geometry 1600x1000 -geometry 2560x1600 -geometry 1024x768 -geometry 1080x800 -geometry 1920x1080 -geometry 1440x900'
vncserver -kill :7
vncserver -kill :8
vncserver -kill :9
